apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: repository-url
      type: string
      description: Repository url
    - name: branch
      type: string
      description: branch
  tasks:
    - name: "git-clone"
      displayName: "Git Task"
      description: "Cloning the url"
      taskRef:
        resolver: hub
        params:
        - name: kind
          value: task
        - name: name
          value: git-clone
        - name: version
          value: "0.9"
      params:
        - name: url
          value: $(params.repository-url)
        - name: revision
          value: $(params.branch) 
      workspaces:
        - name: output
          workspace: source
